name: open_weather_api_client
description: A comprehensive dart library for interfacing with the Open Weather API, providing wrappers for every endpoint served by OpenWeather.
version: 2.0.0
homepage: https://tanzilzubair.github.io
repository: https://github.com/tanzilzubair/open_weather_api_client

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  retry: ^3.1.0
  http: ^0.13.3
  connectivity: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

